Firmware
waterloo-rocketry/cansw_propulsion pull request #1
Opened 2024-06-14 00:45 UTC by JasonBrave

2024-07-06 06:08 UTC, BluCodeGH requested changes

2024-07-06 06:08 UTC, BluCodeGH commented on actuator.c
> +uint8_t actuator_invert = 0;
You should get rid of all the actuator inverting logic. Inverting only makes sense if your CAN commands are OPEN/CLOSE, but our CAN commands are ON/OFF which is well-defined and should never be inverted. This caused a ton of confusion last year, lets pls avoid it this year.

2024-07-06 06:08 UTC, BluCodeGH commented on error_checks.c
> +const float CONVERT_FACTOR = 1e+05 / 4096.0f * 3.3; // 100 V/V multiplier * mV conversion * (raw + continuity correction) / 12bit adc * vref
This isn't correct. An adc raw output of 1 = 1/4096 * 3.3V into adc = 1/4096 * 3.3V / 100 across resistor, this is the inverse of that (and idk where the 1e5 came from). Also remember when you divide by a resistance in milliohms, you end up with mV / mohm = A, not mA! So you want to multiply the conversion factor by 1000 so you have microvolts.

2024-07-06 06:08 UTC, BluCodeGH commented on error_checks.c
>      // Vref: 4.096V, Resolution: 12 bits -> raw ADC value is precisely in mV
This comment (and thus your conversion math) is incorrect.

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
> +#define MAX_BUS_DEAD_TIME_ms 1000 // Unused
This isn't unused?

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
> +    uint32_t last_message_millis = 0; // last time we saw a can message // FIXME reset
FIXME?

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
> +                send_status_ok();
You've got two blocks of duplicated code checking for errors and sending status ok, only have one pls :smiling_face_with_three_hearts:

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
> +#ifdef JASON
Remove this

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
> +// FIXME wtf is this. PRES_TIME_DIFF_ms is defined in the header file to be 250
Remove?

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
>      }
Github wont let me comment lower but remove the random send_status_ok thats after the while loop, we'll never get there.

2024-07-06 06:08 UTC, BluCodeGH commented on main.c
>              if (cmd_type == BUS_DOWN_WARNING) {
Not sure why this code ever existed but we should only ever be changing actuators in response to error conditions or actuator commands, not a bus down warning. Just ignore this message.

2024-07-25 19:26 UTC, KavinSatheeskumar requested changes

2024-07-25 19:26 UTC, KavinSatheeskumar commented on defmplabxtrace.log
Don't include log files in your PR

2024-07-25 19:26 UTC, KavinSatheeskumar commented on actuator.h
> +void actuator_set(enum ACTUATOR_STATE state, uint8_t pin_num);
This is nitpicky, but call it set_actuator_state, just so the naming convention lines up

2024-07-25 19:26 UTC, KavinSatheeskumar commented on actuator.c
> +    /**
Removed commented out code

2024-07-25 19:26 UTC, KavinSatheeskumar commented on actuator.c
> +enum ACTUATOR_STATE get_actuator_state(uint8_t pin_num) {
Function note used

2024-07-25 19:26 UTC, KavinSatheeskumar commented on IOExpanderDriver.c
> +void pca_init() {
Function never used also is empty

2024-07-25 19:26 UTC, KavinSatheeskumar commented on actuator.c
> +uint8_t actuator_states = 0;
We never actually read actuator states, so we should probs remove this variable and just have the set use the pca, no need to maintain the state of the actuator in the code

2024-07-25 19:26 UTC, KavinSatheeskumar commented on actuator.c
> +void actuator_init() {
If we are not using actuator_state, we can get rid of this variable.

Also, even if we do, we can probs add some logic to get_actator_state which avoids an init

2024-07-27 04:38 UTC, KavinSatheeskumar approved these changes

2024-07-27 04:38 UTC, KavinSatheeskumar commented on actuator.c
> +    if (state == 1) {
we could use ternary operator instead of this iff condition

`return (state == 1) ? ACTUATOR_ON : ACTUATOR_OFF`

2024-07-27 04:44 UTC, merged